### ISSUE TITLE
Наверное стоит и его загнать в блок if

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_html-css#13]
https://github.com/lyolka92/epam_html-css/blob/2038100111cb8334ab83b9bcc8c45c92ff03d0c8/script/carousel.js#L37

**Comment by lyolka92** [comment]
Реализовано в [этом](https://github.com/lyolka92/epam_html-css/commit/20803582366cc12b4fb57233ebb531e3115c5191) коммите.
