### ISSUE TITLE
Переделать структуру carousel.js 

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_html-css#14]
Пока сделаем без импорта модулей.
Для изоляции переменных нужно все обернуть в функцию или класс, а потом записать в глобальную переменную инициализирующую функцию

В эту функцию передаем контейнер слайдера
Внутри carousel работаем уже с этим контейром - находим слайды и т.д.

**Comment by lyolka92** [comment]
Реализовано в [этом](https://github.com/lyolka92/epam_html-css/commit/20803582366cc12b4fb57233ebb531e3115c5191) коммите.
