### ISSUE TITLE
Можно без массива, сразу в шаблонной строке все делать

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_html-css#15]
https://github.com/lyolka92/epam_html-css/blob/2038100111cb8334ab83b9bcc8c45c92ff03d0c8/script/popup.js#L17

А еще можно через https://developer.mozilla.org/ru/docs/Web/HTML/Element/template

**Comment by lyolka92** [comment]
Испправлено в [этом](https://github.com/lyolka92/epam_html-css/commit/c98f4f6126faa13ca8ccb5d9aba6b097b377ae51) коммите
