### ISSUE TITLE
Можно искать в самом попапе и не по id, а по классу

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_html-css#17]
https://github.com/lyolka92/epam_html-css/blob/2038100111cb8334ab83b9bcc8c45c92ff03d0c8/script/popup.js#L43

```
('click', event => {
   this.close();
})
```
event - не используется

если написать function() { this.close(); }, вместо стрелочной функции, будет другое поведение

**Comment by lyolka92** [comment]
Испправлено в [этом](https://github.com/lyolka92/epam_html-css/commit/c98f4f6126faa13ca8ccb5d9aba6b097b377ae51) коммите
