### ISSUE TITLE
Сделать импорты в scss

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_html-css#7]
Нужно чтобы в html подключался только один css.

**Comment by lyolka92** [comment]
Исправлено [в бранче с фиксами](https://github.com/lyolka92/epam_html-css/tree/fixes_from_08-09-2020).
Только один css подключить не получилось, поскольку у меня есть отдельные стили для каждой из страниц => на каждой странице подключен общий styles.css и персональный page_<page-name>.css.
