### ISSUE TITLE
Добавить css и css.map в исключения для git

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_html-css#8]
Чтобы не загромождать гит не нужными файлами. В корне репозитория создать README.md с описанием того, что для проекта нужен sass и нужную команды для компиляции sass в css

**Comment by lyolka92** [comment]
Ранее .css и .css.map файлы генерировались моей IDE. В связи с добавлением файлов в gitignore пришлось удалить автоматически сгенерированные файлы и искать менее ленивый путь по генерации .css из .scss.
Как результат, в рамках данной issue был подключен galp ([этот](https://github.com/lyolka92/epam_html-css/commit/e55343ed31905d0003a62c656bf21dca2322f649) коммит), файлы (с учётом нового пути) добавлены в gitignore ([этот](https://github.com/lyolka92/epam_html-css/commit/ea5db7784de85ba2f5d5237b2b7feff9721ce16a) коммит) и, наконец, удалены css файлы ([этот](https://github.com/lyolka92/epam_html-css/commit/b7080ea18567268d088f6c39cc0feff739dc06a7) коммит).
