### ISSUE TITLE
Можно выделить общий класс для этих элементов

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_html-css#9]
https://github.com/lyolka92/epam_html-css/blob/2038100111cb8334ab83b9bcc8c45c92ff03d0c8/styles/component_menu.scss#L132

**Comment by lyolka92** [comment]
Исправлено в [этом](https://github.com/lyolka92/epam_html-css/commit/90e138249338c23164aaea795dc05a61566c5ad0) коммите.
Дополнительно вынесла в отдельные классы "расцветку" меню для разных страниц, как вчера обсуждали ([этот](https://github.com/lyolka92/epam_html-css/commit/9fd7c0fb2b7965f7611299c4b5813dd3f672a5a8) коммит).
